name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  BUILD_RELEASE_PATH: ./target/release/kvmm
  RELEASE_DIR_NAME: release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Test
        run: cat $BUILD_RELEASE_PATH
      - name: mkdir
        run: mkdir $RELEASE_DIR_NAME
      - name: move kvmm
        run: mv $BUILD_RELEASE_PATH $RELEASE_DIR_NAME
      - name: init memo.json
        run: echo "{}" >> $RELEASE_DIR_NAME/memo.json
      - name: create tar.gz
        run: tar -zcvf $RELEASE_DIR_NAME.tar.gz $RELEASE_DIR_NAME
      - name: Test
        run: cat $RELEASE_DIR_NAME.tar.gz
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release.tar.gz
